#!/usr/bin/env php
<?php

ini_set('display_errors', 1);
error_reporting(E_ERROR | E_WARNING | E_PARSE);

$projectRootPath = getcwd();
$composerJsonPath = $projectRootPath . '/composer.json';

if (!is_file($composerJsonPath)) {
    throw new \UnexpectedValueException('No composer.json in root path: ' . $projectRootPath);
}

$composerConfig = json_decode(file_get_contents($composerJsonPath));
if ($composerConfig === null) {
    throw new \UnexpectedValueException('Could not parse composer.json.');
}

if (property_exists($composerConfig, 'config')) {
    $config = $composerConfig->config;
    $vendorDirectory = $config->{'vendor-dir'} ?? './vendor';
} else {
    $vendorDirectory = './vendor';
}

require $vendorDirectory . '/autoload.php';

$entryPoint = new \Z3\PHP\Development\EntryPoint();
$entryPoint->run();
